# Generated by Django 6.0.4 on 2026-04-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ALL USERS', 'ALL USERS'), ('PENDING USERS', 'PENDING USERS'), ('PENDING LOANS', 'PENDING LOANS'), ('APPROVED LOANS', 'APPROVED LOANS'), ('FUNDED LOANS', 'FUNDED LOANS'), ('RUNNING LOANS', 'RUNNING LOANS'), ('DEAFULT LOANS', 'DEAFULT LOANS'), ('RECOVERY LOANS', 'RECOVERY LOANS'), ('BAD LOANS', 'BAD LOANS')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('recipients_personal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('recipients_work', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('emailto_personal', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('emailto_work', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('read_by_app', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('read_by_personal_email', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('read_by_work_email', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('email_sent', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('email_not_sent', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('email_sent_work', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('email_not_sent_work', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin1.location')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgq', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('msglog', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('msgbyemail', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('msg_not_emailed', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('msgbyemail_work', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('msg_not_emailed_work', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('readonline', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('reademail', models.CharField(blank=True, default='', max_length=1555, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
