# Generated by Django 6.0.4 on 2026-04-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LOAN REQUIREMENTS', 'LOAN REQUIREMENTS'), ('PENDING LOAN', 'PENDING LOAN'), ('LOAN REPAYMENT', 'LOAN REPAYMENT'), ('LOAN ISSUE', 'LOAN ISSUE'), ('ACCOUNT ACTIVATION', 'ACCOUNT ACTIVATION'), ('WEB APP USAGE', 'WEB APP USAGE')], max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=555, null=True)),
                ('threadlog', models.CharField(blank=True, max_length=1555, null=True)),
                ('threadq', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thread', models.CharField(blank=True, max_length=1555, null=True)),
                ('thread_content', models.CharField(blank=True, max_length=555, null=True)),
                ('responder', models.CharField(blank=True, max_length=55, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportticket')),
            ],
        ),
    ]
