"""
Django settings for wincorpfinance project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from celery.schedules import crontab
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^-j1i)*(_82lzp7x0ywh^i99ufeis5$y)g+v$y)s4o)dy_+b1y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#change in production environment for ip and domain(s)
ALLOWED_HOSTS = ['wincorpfinance.com.pg','www.wincorpfinance.com.pg','45.77.237.180',]


#site settings
SITE_NAME = 'WINCORP FINANCE'
DOMAIN = 'https://www.wincorpfinance.com.pg' # this will reduce the Sites framework db call.
DOMAIN_DNS = 'wincorpfinance.com.pg'  #used here  email = f'{random_email}@{settings.DOMAIN_DNS}' in staff.views.py
PREFIX = 'WCF' # prefix for all the E-Intfinance generated codes

MAIN_COLOR = '#6bb10d' #A751A7 #change out #3bd671   #website color was this: #1acc8d #040677

# DO NOT FORGET : 'django.contrib.humanize', in apps 

SUPPORT_EMAIL = 'support@wincorpfinance.com.pg'
ADMIN_RECEIVER = 'loans@wincorpfinance.com.pg' #admin to receive notifications
TEST_RECEIVER = 'loans@wincorpfinance.com.pg' # development TEST admin to receive notifications
TEST_USER = 'loans@wincorpfinance.com.pg' #TEST user to receive notifications

#DCC
LUID = 'WCF55XG608'
DCC_PROFILE_ID = 9
DCC_ENDPOINT = 'www.dc.com.pg'

#Public Service Deduction Code
ALESCO_DC = 'WCFCD'
COMPANY_NAME = 'WINCORP FINANCE'
LOAN_TYPES = 1

INTEREST_TYPE = 'CUSTOM'
FIXED_INTEREST_RATE = 0.2
VARIABLE_INTEREST_RATE = 0.0125

#loan application
PROCESSING_FEE_CHARGABLE = 'NO'
PROCESSING_FEE = Decimal(0.0)
LOAN_APPLICATION_FEE = Decimal(0.0)
LOAN_MAX_AMOUNT = Decimal(5000.00)
LOAN_MIN_AMOUNT = Decimal(300.00)
DEFAULT_INTEREST_RATE = Decimal(0.0)
DEFAULT_INTEREST_CALCULATION_MERCY_DAYS = 7

#minmax_settings
MIN_FN = 1
MAX_FN = 30
MIN_AMOUNT = 300
MAX_AMOUNT =5000
INCREMENT_AMOUNT = 100
INCREMENT_FN = 1

#REPAYMENT SETTINGS
TOTAL_ALLOWABLE_TOEAS = Decimal(0.01)
LOAN_COMPLETION_BALANCE = Decimal(0.01)


#VARIABLE INTEREST
'''
For all our personal loans or “PayDay” loans they are subject to the various rates based on the fortnightly repayment period:
Minimum two fortnight repayment period 30%
Three to four fortnight repayment period 40%
Five to ten fortnight repayment period 50%
'''
INTEREST1 = Decimal(0.3)
INTEREST2 = Decimal(0.4)
INTEREST3 = Decimal(0.5)

#BANK ACCOUNT INFORMATION
BANK1 = 'BSP'
BANK1_ACC_NAME = 'WINCORP FINANCE LIMITED'
BANK1_ACC_NUM = '7019635718'
BANK1_BRANCH = 'PORT MORESBY'
BANK1_BSB = '088907'
SWIFT = 'BOSPPGPM'

#BANK ACCOUNT INFORMATION
BANK2 = 'KINA'
BANK2_ACC_NAME = 'WINCORP FINANCE LIMITED'
BANK2_ACC_NUM = '1001439485'
BANK2_BRANCH = 'PORT MORESBY'
BANK2_BSB = '088294'

#email addresses
ADMIN_EMAILS = ['app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
APPLICATION_FORM_EMAIL = ['loans@wincorpfinance.com.pg','app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
FUNDING_NOTICE_EMAIL = ['accounts@wincorpfinance.com.pg','app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
REPAYMENT_EMAIL = ['accounts@wincorpfinance.com.pg','app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
REPORTS_EMAIL = ['reports@wincorpfinance.com.pg','app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
DEFAULTS_EMAIL = ['recovery@wincorpfinance.com.pg','app@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']
NOTIFICATION_EMAILS = ['loans@wincorpfinance.com.pg', 'notifications@wincorpfinance.com.pg','loans@wincorpfinance.com.pg']

DIRECTORS = []

DEFAULT_SENDER_EMAIL = 'WINCORP FINANCE <app@wincorpfinance.com.pg>'
#emails
REPLY_TO_EMAIL = 'loans@wincorpfinance.com.pg'
CC_EMAILS = ['loans@wincorpfinance.com.pg',]
BCC_EMAILS = ['dev@webmasta.com.pg',]


#LOAN HANDLING
SYSTEM_TYPE = 'ONE_LOAN_PER_CUSTOMER' #one statement for one customer with all loans treated as one 
MULTIPLE_LOANS = 'YES' #additional applications can be accepted with a current running loan

# for userprofile model to work
AUTH_USER_MODEL = 'accounts.User'






# Application definition
INSTALLED_APPS = [
    # 'jet.dashboard',
    # 'jet',
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'django_select2',
    'debug_toolbar',
    'django_recaptcha',
    'ckeditor',
    'ckeditor_uploader',
    'wkhtmltopdf',
    'crispy_forms',
    'crispy_bootstrap5',  # Forgetting this was probably your error
    'fontawesomefree',
    'material',
    'import_export',
    'accounts',
    'admin1',
    'loan', 
    'staff',
    'message',
    'support',
    'custom',
    'api',
    'report',
    'dcc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'wincorp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wincorp.wsgi.application'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# WKHTMLTOPDF
WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'

# HTML TO PDF
WKHTMLTOPDF_CMD_OPTIONS = {
    'quiet': True,
}

if os.name != 'nt':
    WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'
else:
    WKHTMLTOPDF_DEBUG = True

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wincorpfinance',
        'USER': 'root',
        'PASSWORD': 'wweht5&Wfefs24@',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Etc/GMT-10'
USE_I18N = True
USE_TZ = True
DATE_INPUT_FORMATS = ['%d-%m-%Y']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#Static Settings
STATIC_URL = '/static/'
STATIC_ROOT = '/root/wincorp/static/'  #activate when on server environment
#STATIC_ROOT = 'static'   #comment out when on server
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_files'),
]

#MEDIA Conf
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')   #check previous settings if media uploads dont work MEDIA_ROOT = 'uploads'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# EMAIL SERVER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'mail.trupngfinance.com.pg'
EMAIL_HOST_USER = 'app@trupngfinance.com.pg'
EMAIL_HOST_PASSWORD = 'TPfL445Y@cmx'
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# celery settings
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_TIMEZONE = 'Etc/GMT-10'

CELERY_BEAT_SCHEDULE = {

    'notify_customers': {
        'task': 'message.tasks.notify_customers',
        'schedule': 20*60*60, # to schedule: crontab(day_of_week=1, hour=7, minute=30)   #crontab(minute='*/15) means every 15minutes  # 5 means seconds
        'args': ['Hello Celery Test Message'],
        # 'kwargs': { key_value_pairs },
    },
    'payments_expected_today': {
        'task': 'loan.tasks.payments_expected_today',
        'schedule': 2*60, 
    },
    
    'reminded_today_reset': {
        'task': 'loan.tasks.reminded_today_reset',
        'schedule': 25*60*60,
    },
    'default_classification': {
        'task': 'loan.tasks.default_classification',
        'schedule': 10*60,
    },

    #send repayment reminder
    'auto_send_repayment_reminder': {
        'task': 'loan.tasks.auto_send_repayment_reminder',
        'schedule': crontab(hour=8, minute=50), 
    },

    #run defaults
    'auto_run_defaults': {
        'task': 'loan.tasks.auto_run_defaults',
        'schedule': crontab(minute='*/30'), 
    }#,

    #run test
    #'auto_send_test_email': {
    #    'task': 'loan.tasks.auto_send_test_email',
    #    'schedule': crontab(hour='*/35'), 
    #}

}

#recaptcha
RECAPTCHA_PUBLIC_KEY = '6LcNWuYsAAAAAF55h_9AFGb4KQDjETRLWOdT05uq'
RECAPTCHA_PRIVATE_KEY = '6LcNWuYsAAAAAP-Sd9URueDMI4wu-LYWUJtEB9DX'
RECAPTCHA_RESPONSE_KEY = 'g-recaptcha-response'
RECAPTCHA_DOMAIN = 'www.recaptcha.net'

#django rest framework    
REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
}

#CKEditor Settings
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },
}

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "WINCORP FINANCE",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "WINCORP FINANCE",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": 'WINCORP FINANCE',

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "clientfiles/wincorplogo.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to WINCORP FINANCE",

    # Copyright on the footer
    "copyright": "WINCORP FINANCE@WEBMASTA",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index",
            "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://www.webmasta.com.pg/", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

## JET THEMES
'''
JET_THEMES = [
    {
        'theme': 'default', # theme folder name
        'color': '#47bac1', # color of the theme's button in user menu
        'title': 'Default' # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green',
        'font-size': '20px',
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

'''
