# Generated by Django 6.0.4 on 2026-04-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_name', models.CharField(blank=True, max_length=30, null=True)),
                ('loanref_prefix', models.CharField(blank=True, help_text="For example, Instabuxx uses 'iBX' in front for all loan refs.", max_length=5, null=True, verbose_name='Loan Reference Prefix:')),
                ('admin_email_addresses', models.CharField(blank=True, default='app@trupngfinance.com.pg', help_text='Email Addresses that will receive system admin notifications. Enter email addresses separated by a comma. Eg: info@loanmasta.com,admin@loanmasta.com. Make sure there are no spaces after the comma', max_length=250, verbose_name='Admin Email Addresses:')),
                ('default_from_email', models.CharField(blank=True, default='app@trupngfinance.com.pg', help_text='Email Address that will send all notifications to the user.', max_length=100, verbose_name='Default From Email:')),
                ('support_email', models.CharField(blank=True, default='support@wincorpfinance.com.pg', help_text='Email Address that will receive all support requests.', max_length=100, verbose_name='Support Email:')),
                ('credit_check', models.CharField(blank=True, choices=[('NO', 'NO - We will decide'), ('YES', 'YES - Automatic')], help_text='If you set this to yes, Loan Application Decision will be made automatically based on your customer credit threshold setting.', max_length=255, null=True, verbose_name='Automatic Credit Check:')),
                ('approval_credit_threshold', models.DecimalField(blank=True, decimal_places=3, help_text="User's with credit rating above this will have loan applications allowed if credit check is set to automatic.", max_digits=5, null=True, verbose_name='Approval Credit Threshold:')),
                ('percentage_of_gross', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Percentage of Gross allowable:')),
                ('interest_type', models.CharField(blank=True, choices=[('FIXED', 'FIXED'), ('VARIABLE', 'VARIABLE'), ('CUSTOM', 'CUSTOM')], max_length=255, null=True, verbose_name='Interest Type:')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, help_text='If interest is fixed, enter standard interest, eg: 30%. If Interest is variable, enter per term interest. Eg, 1.25% per fortnight', max_digits=5, null=True, verbose_name='Interest Rate in Percentage:')),
                ('processing_fee', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=255, null=True, verbose_name='Processing Fee:')),
                ('processing_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('default_interest_rate', models.DecimalField(blank=True, decimal_places=3, help_text='In percentage of repayment amount, say 20 for 20% of repayment amount', max_digits=5, null=True, verbose_name='Default Interest Rate:')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(choices=[('AROB', 'AROB'), ('CENTRAL', 'CENTRAL'), ('ENGA', 'ENGA'), ('EAST SEPIK', 'EAST SEPIK'), ('EHP', 'EHP'), ('ENB', 'ENBP'), ('HELA', 'HELA'), ('JIWAKA', 'JIWAKA'), ('MADANG', 'MADANG'), ('MANUS', 'MANUS'), ('MILNE BAY', 'MILNE BAY'), ('MOROBE', 'MOROBE'), ('NCD', 'NCD'), ('NEW IRELAND', 'NEW IRELAND'), ('ORO', 'ORO'), ('SHP', 'SHP'), ('SIMBU', 'SIMBU'), ('WESTERN', 'WESTERN'), ('WEST SEPIK', 'WEST SEPIK'), ('WHP', 'WHP'), ('WNB', 'WNBP')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('loans', models.IntegerField(blank=True, default=0, null=True)),
                ('loans_in_default', models.IntegerField(blank=True, default=0, null=True)),
                ('funded', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('repayment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('arrears', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('outstanding', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('in_recovery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('customers', models.IntegerField(blank=True, default=0, null=True)),
                ('customers_with_loan', models.IntegerField(blank=True, default=0, null=True)),
                ('customers_in_recovery', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
